// AUTO-GENERATED notification templates (28 languages).
// Keyed TEMPLATES[lang][key] = string. Used by localized.js →
// localizedNotification(). Edit English in source and regenerate.
export const TEMPLATES = {
  "en": {
    "newMessage_title": "New message",
    "newMessage_body": "{handle} sent you a message",
    "photoUnlock_title": "Photo unlock request",
    "photoUnlock_body": "{handle} wants to unlock photos with you",
    "incomingCallVoice_title": "Incoming voice call",
    "incomingCallVideo_title": "Incoming video call",
    "incomingCall_body": "{handle} is calling you",
    "likeRejected_title": "Not a match this time",
    "likeRejected_body": "{handle} passed on your like",
    "newLike_title": "New Like!",
    "newSuperLike_title": "New Super Like!",
    "newLike_body": "{handle} liked your profile",
    "newMatch_title": "It's a Match!",
    "newMatch_body": "You matched with {handle}",
    "weeklySuperLikes_title": "Your weekly Super Likes are here 💫",
    "weeklySuperLikes_body": "You've got {count} Super Likes to use this week.",
    "weeklyBoost_title": "Your weekly Boost is ready 🚀",
    "weeklyBoost_body": "Activate it to jump to the top of the deck for 30 minutes.",
    "supportReply_title": "Support replied"
  },
  "de": {
    "newMessage_title": "Neue Nachricht",
    "newMessage_body": "{handle} hat dir eine Nachricht geschickt",
    "photoUnlock_title": "Anfrage zum Foto-Freischalten",
    "photoUnlock_body": "{handle} möchte Fotos mit dir freischalten",
    "incomingCallVoice_title": "Eingehender Sprachanruf",
    "incomingCallVideo_title": "Eingehender Videoanruf",
    "incomingCall_body": "{handle} ruft dich an",
    "likeRejected_title": "Diesmal kein Match",
    "likeRejected_body": "{handle} hat dein Like abgelehnt",
    "newLike_title": "Neues Like!",
    "newSuperLike_title": "Neuer Super Like!",
    "newLike_body": "{handle} mag dein Profil",
    "newMatch_title": "Es ist ein Match!",
    "newMatch_body": "Du hast ein Match mit {handle}",
    "weeklySuperLikes_title": "Deine wöchentlichen Super Likes sind da 💫",
    "weeklySuperLikes_body": "Du hast diese Woche {count} Super Likes zum Verschenken.",
    "weeklyBoost_title": "Dein wöchentlicher Boost ist bereit 🚀",
    "weeklyBoost_body": "Aktiviere ihn und lande 30 Minuten lang ganz oben im Deck.",
    "supportReply_title": "Support hat geantwortet"
  },
  "nl": {
    "newMessage_title": "Nieuw bericht",
    "newMessage_body": "{handle} heeft je een bericht gestuurd",
    "photoUnlock_title": "Verzoek om foto's te ontgrendelen",
    "photoUnlock_body": "{handle} wil foto's met je ontgrendelen",
    "incomingCallVoice_title": "Inkomende spraakoproep",
    "incomingCallVideo_title": "Inkomende video-oproep",
    "incomingCall_body": "{handle} belt je",
    "likeRejected_title": "Deze keer geen match",
    "likeRejected_body": "{handle} heeft je like afgewezen",
    "newLike_title": "Nieuwe Like!",
    "newSuperLike_title": "Nieuwe Super Like!",
    "newLike_body": "{handle} vindt je profiel leuk",
    "newMatch_title": "Het is een Match!",
    "newMatch_body": "Je hebt een match met {handle}",
    "weeklySuperLikes_title": "Je wekelijkse Super Likes zijn er 💫",
    "weeklySuperLikes_body": "Je hebt {count} Super Likes om deze week te gebruiken.",
    "weeklyBoost_title": "Je wekelijkse Boost staat klaar 🚀",
    "weeklyBoost_body": "Activeer hem en spring 30 minuten lang naar de top van de stapel.",
    "supportReply_title": "Support heeft geantwoord"
  },
  "sv": {
    "newMessage_title": "Nytt meddelande",
    "newMessage_body": "{handle} skickade ett meddelande till dig",
    "photoUnlock_title": "Begäran om att låsa upp foton",
    "photoUnlock_body": "{handle} vill låsa upp foton med dig",
    "incomingCallVoice_title": "Inkommande röstsamtal",
    "incomingCallVideo_title": "Inkommande videosamtal",
    "incomingCall_body": "{handle} ringer dig",
    "likeRejected_title": "Ingen matchning den här gången",
    "likeRejected_body": "{handle} tackade nej till din gillning",
    "newLike_title": "Ny Like!",
    "newSuperLike_title": "Ny Super Like!",
    "newLike_body": "{handle} gillade din profil",
    "newMatch_title": "Det är en Match!",
    "newMatch_body": "Du matchade med {handle}",
    "weeklySuperLikes_title": "Dina veckovisa Super Likes är här 💫",
    "weeklySuperLikes_body": "Du har {count} Super Likes att använda den här veckan.",
    "weeklyBoost_title": "Din veckovisa Boost är redo 🚀",
    "weeklyBoost_body": "Aktivera den och hoppa högst upp i leken i 30 minuter.",
    "supportReply_title": "Supporten svarade"
  },
  "no": {
    "newMessage_title": "Ny melding",
    "newMessage_body": "{handle} sendte deg en melding",
    "photoUnlock_title": "Forespørsel om å låse opp bilder",
    "photoUnlock_body": "{handle} vil låse opp bilder med deg",
    "incomingCallVoice_title": "Innkommende taleanrop",
    "incomingCallVideo_title": "Innkommende videoanrop",
    "incomingCall_body": "{handle} ringer deg",
    "likeRejected_title": "Ingen match denne gangen",
    "likeRejected_body": "{handle} takket nei til din like",
    "newLike_title": "Ny Like!",
    "newSuperLike_title": "Ny Super Like!",
    "newLike_body": "{handle} likte profilen din",
    "newMatch_title": "Det er en Match!",
    "newMatch_body": "Du matchet med {handle}",
    "weeklySuperLikes_title": "Dine ukentlige Super Likes er her 💫",
    "weeklySuperLikes_body": "Du har {count} Super Likes å bruke denne uken.",
    "weeklyBoost_title": "Din ukentlige Boost er klar 🚀",
    "weeklyBoost_body": "Aktiver den og hopp til toppen av bunken i 30 minutter.",
    "supportReply_title": "Support svarte"
  },
  "da": {
    "newMessage_title": "Ny besked",
    "newMessage_body": "{handle} sendte dig en besked",
    "photoUnlock_title": "Anmodning om at låse fotos op",
    "photoUnlock_body": "{handle} vil låse fotos op med dig",
    "incomingCallVoice_title": "Indgående taleopkald",
    "incomingCallVideo_title": "Indgående videoopkald",
    "incomingCall_body": "{handle} ringer til dig",
    "likeRejected_title": "Intet match denne gang",
    "likeRejected_body": "{handle} sagde nej til dit like",
    "newLike_title": "Nyt Like!",
    "newSuperLike_title": "Nyt Super Like!",
    "newLike_body": "{handle} kunne lide din profil",
    "newMatch_title": "Det er et Match!",
    "newMatch_body": "Du matchede med {handle}",
    "weeklySuperLikes_title": "Dine ugentlige Super Likes er her 💫",
    "weeklySuperLikes_body": "Du har {count} Super Likes at bruge i denne uge.",
    "weeklyBoost_title": "Dit ugentlige Boost er klar 🚀",
    "weeklyBoost_body": "Aktivér det og spring til toppen af bunken i 30 minutter.",
    "supportReply_title": "Support svarede"
  },
  "pl": {
    "newMessage_title": "Nowa wiadomość",
    "newMessage_body": "{handle} wysłał(a) Ci wiadomość",
    "photoUnlock_title": "Prośba o odblokowanie zdjęć",
    "photoUnlock_body": "{handle} chce odblokować z Tobą zdjęcia",
    "incomingCallVoice_title": "Połączenie głosowe",
    "incomingCallVideo_title": "Połączenie wideo",
    "incomingCall_body": "{handle} dzwoni do Ciebie",
    "likeRejected_title": "Tym razem bez dopasowania",
    "likeRejected_body": "{handle} nie odwzajemnił(a) polubienia",
    "newLike_title": "Nowe polubienie!",
    "newSuperLike_title": "Nowe Super polubienie!",
    "newLike_body": "{handle} polubił(a) Twój profil",
    "newMatch_title": "To dopasowanie!",
    "newMatch_body": "Masz dopasowanie z {handle}",
    "weeklySuperLikes_title": "Twoje cotygodniowe Super polubienia są tutaj 💫",
    "weeklySuperLikes_body": "Masz {count} Super polubień do wykorzystania w tym tygodniu.",
    "weeklyBoost_title": "Twój cotygodniowy Boost jest gotowy 🚀",
    "weeklyBoost_body": "Aktywuj go, aby na 30 minut przeskoczyć na szczyt talii.",
    "supportReply_title": "Wsparcie odpowiedziało"
  },
  "cs": {
    "newMessage_title": "Nová zpráva",
    "newMessage_body": "{handle} ti poslal(a) zprávu",
    "photoUnlock_title": "Žádost o odemčení fotek",
    "photoUnlock_body": "{handle} chce s tebou odemknout fotky",
    "incomingCallVoice_title": "Příchozí hovor",
    "incomingCallVideo_title": "Příchozí videohovor",
    "incomingCall_body": "{handle} ti volá",
    "likeRejected_title": "Tentokrát to nevyšlo",
    "likeRejected_body": "{handle} tvůj lajk neopětoval(a)",
    "newLike_title": "Nový lajk!",
    "newSuperLike_title": "Nový Super lajk!",
    "newLike_body": "{handle} olajkoval(a) tvůj profil",
    "newMatch_title": "Máte shodu!",
    "newMatch_body": "Máš shodu s {handle}",
    "weeklySuperLikes_title": "Tvé týdenní Super lajky jsou tady 💫",
    "weeklySuperLikes_body": "Máš {count} Super lajků k využití tento týden.",
    "weeklyBoost_title": "Tvůj týdenní Boost je připraven 🚀",
    "weeklyBoost_body": "Aktivuj ho a na 30 minut vyskoč na vrchol balíčku.",
    "supportReply_title": "Podpora odpověděla"
  },
  "sk": {
    "newMessage_title": "Nová správa",
    "newMessage_body": "{handle} ti poslal(a) správu",
    "photoUnlock_title": "Žiadosť o odomknutie fotiek",
    "photoUnlock_body": "{handle} chce s tebou odomknúť fotky",
    "incomingCallVoice_title": "Prichádzajúci hovor",
    "incomingCallVideo_title": "Prichádzajúci videohovor",
    "incomingCall_body": "{handle} ti volá",
    "likeRejected_title": "Tentoraz to nevyšlo",
    "likeRejected_body": "{handle} tvoj lajk neopätoval(a)",
    "newLike_title": "Nový lajk!",
    "newSuperLike_title": "Nový Super lajk!",
    "newLike_body": "{handle} olajkoval(a) tvoj profil",
    "newMatch_title": "Máte zhodu!",
    "newMatch_body": "Máš zhodu s {handle}",
    "weeklySuperLikes_title": "Tvoje týždenné Super lajky sú tu 💫",
    "weeklySuperLikes_body": "Máš {count} Super lajkov na využitie tento týždeň.",
    "weeklyBoost_title": "Tvoj týždenný Boost je pripravený 🚀",
    "weeklyBoost_body": "Aktivuj ho a na 30 minút vyskoč na vrchol balíčka.",
    "supportReply_title": "Podpora odpovedala"
  },
  "sl": {
    "newMessage_title": "Novo sporočilo",
    "newMessage_body": "{handle} ti je poslal(a) sporočilo",
    "photoUnlock_title": "Prošnja za odklep fotografij",
    "photoUnlock_body": "{handle} želi s teboj odkleniti fotografije",
    "incomingCallVoice_title": "Dohodni glasovni klic",
    "incomingCallVideo_title": "Dohodni videoklic",
    "incomingCall_body": "{handle} te kliče",
    "likeRejected_title": "Tokrat ni ujemanja",
    "likeRejected_body": "{handle} ni vrnil(a) tvojega všečka",
    "newLike_title": "Nov všeček!",
    "newSuperLike_title": "Nov Super všeček!",
    "newLike_body": "{handle} je všečkal(a) tvoj profil",
    "newMatch_title": "Ujemanje!",
    "newMatch_body": "Ujemaš se z {handle}",
    "weeklySuperLikes_title": "Tvoji tedenski Super všečki so tukaj 💫",
    "weeklySuperLikes_body": "Ta teden imaš na voljo {count} Super všečkov.",
    "weeklyBoost_title": "Tvoj tedenski Boost je pripravljen 🚀",
    "weeklyBoost_body": "Aktiviraj ga in za 30 minut skoči na vrh kupa.",
    "supportReply_title": "Podpora je odgovorila"
  },
  "fr": {
    "newMessage_title": "Nouveau message",
    "newMessage_body": "{handle} vous a envoyé un message",
    "photoUnlock_title": "Demande de déverrouillage de photos",
    "photoUnlock_body": "{handle} veut déverrouiller ses photos avec vous",
    "incomingCallVoice_title": "Appel vocal entrant",
    "incomingCallVideo_title": "Appel vidéo entrant",
    "incomingCall_body": "{handle} vous appelle",
    "likeRejected_title": "Pas de match cette fois",
    "likeRejected_body": "{handle} n'a pas donné suite à votre like",
    "newLike_title": "Nouveau Like !",
    "newSuperLike_title": "Nouveau Super Like !",
    "newLike_body": "{handle} a aimé votre profil",
    "newMatch_title": "C'est un Match !",
    "newMatch_body": "Vous avez matché avec {handle}",
    "weeklySuperLikes_title": "Vos Super Likes de la semaine sont là 💫",
    "weeklySuperLikes_body": "Vous avez {count} Super Likes à utiliser cette semaine.",
    "weeklyBoost_title": "Votre Boost de la semaine est prêt 🚀",
    "weeklyBoost_body": "Activez-le pour passer en tête du deck pendant 30 minutes.",
    "supportReply_title": "Le support a répondu"
  },
  "es": {
    "newMessage_title": "Nuevo mensaje",
    "newMessage_body": "{handle} te ha enviado un mensaje",
    "photoUnlock_title": "Solicitud para desbloquear fotos",
    "photoUnlock_body": "{handle} quiere desbloquear fotos contigo",
    "incomingCallVoice_title": "Llamada de voz entrante",
    "incomingCallVideo_title": "Videollamada entrante",
    "incomingCall_body": "{handle} te está llamando",
    "likeRejected_title": "Esta vez no hubo match",
    "likeRejected_body": "{handle} pasó de tu like",
    "newLike_title": "¡Nuevo Like!",
    "newSuperLike_title": "¡Nuevo Super Like!",
    "newLike_body": "A {handle} le gustó tu perfil",
    "newMatch_title": "¡Es un Match!",
    "newMatch_body": "Has hecho match con {handle}",
    "weeklySuperLikes_title": "Tus Super Likes de la semana ya están aquí 💫",
    "weeklySuperLikes_body": "Tienes {count} Super Likes para usar esta semana.",
    "weeklyBoost_title": "Tu Boost de la semana está listo 🚀",
    "weeklyBoost_body": "Actívalo para saltar a lo más alto del deck durante 30 minutos.",
    "supportReply_title": "Soporte respondió"
  },
  "it": {
    "newMessage_title": "Nuovo messaggio",
    "newMessage_body": "{handle} ti ha inviato un messaggio",
    "photoUnlock_title": "Richiesta di sblocco foto",
    "photoUnlock_body": "{handle} vuole sbloccare le foto con te",
    "incomingCallVoice_title": "Chiamata vocale in arrivo",
    "incomingCallVideo_title": "Videochiamata in arrivo",
    "incomingCall_body": "{handle} ti sta chiamando",
    "likeRejected_title": "Nessun match stavolta",
    "likeRejected_body": "{handle} ha lasciato perdere il tuo like",
    "newLike_title": "Nuovo Like!",
    "newSuperLike_title": "Nuovo Super Like!",
    "newLike_body": "A {handle} è piaciuto il tuo profilo",
    "newMatch_title": "È un Match!",
    "newMatch_body": "Hai fatto match con {handle}",
    "weeklySuperLikes_title": "I tuoi Super Like della settimana sono arrivati 💫",
    "weeklySuperLikes_body": "Hai {count} Super Like da usare questa settimana.",
    "weeklyBoost_title": "Il tuo Boost della settimana è pronto 🚀",
    "weeklyBoost_body": "Attivalo per balzare in cima al deck per 30 minuti.",
    "supportReply_title": "L'assistenza ha risposto"
  },
  "pt": {
    "newMessage_title": "Nova mensagem",
    "newMessage_body": "{handle} enviou uma mensagem para você",
    "photoUnlock_title": "Pedido para desbloquear fotos",
    "photoUnlock_body": "{handle} quer desbloquear fotos com você",
    "incomingCallVoice_title": "Chamada de voz recebida",
    "incomingCallVideo_title": "Chamada de vídeo recebida",
    "incomingCall_body": "{handle} está te ligando",
    "likeRejected_title": "Sem match desta vez",
    "likeRejected_body": "{handle} não correspondeu ao seu like",
    "newLike_title": "Novo Like!",
    "newSuperLike_title": "Novo Super Like!",
    "newLike_body": "{handle} curtiu o seu perfil",
    "newMatch_title": "É um Match!",
    "newMatch_body": "Você deu match com {handle}",
    "weeklySuperLikes_title": "Seus Super Likes da semana chegaram 💫",
    "weeklySuperLikes_body": "Você tem {count} Super Likes para usar esta semana.",
    "weeklyBoost_title": "Seu Boost da semana está pronto 🚀",
    "weeklyBoost_body": "Ative-o para pular para o topo do deck por 30 minutos.",
    "supportReply_title": "O suporte respondeu"
  },
  "ro": {
    "newMessage_title": "Mesaj nou",
    "newMessage_body": "{handle} ți-a trimis un mesaj",
    "photoUnlock_title": "Cerere de deblocare a pozelor",
    "photoUnlock_body": "{handle} vrea să deblocheze pozele cu tine",
    "incomingCallVoice_title": "Apel vocal primit",
    "incomingCallVideo_title": "Apel video primit",
    "incomingCall_body": "{handle} te sună",
    "likeRejected_title": "Fără match de data asta",
    "likeRejected_body": "{handle} a trecut peste like-ul tău",
    "newLike_title": "Like nou!",
    "newSuperLike_title": "Super Like nou!",
    "newLike_body": "{handle} ți-a apreciat profilul",
    "newMatch_title": "E Match!",
    "newMatch_body": "Ai făcut match cu {handle}",
    "weeklySuperLikes_title": "Super Like-urile tale săptămânale au sosit 💫",
    "weeklySuperLikes_body": "Ai {count} Super Like-uri de folosit săptămâna asta.",
    "weeklyBoost_title": "Boost-ul tău săptămânal e gata 🚀",
    "weeklyBoost_body": "Activează-l ca să sari în capul listei timp de 30 de minute.",
    "supportReply_title": "Suportul a răspuns"
  },
  "hr": {
    "newMessage_title": "Nova poruka",
    "newMessage_body": "{handle} ti je poslao/la poruku",
    "photoUnlock_title": "Zahtjev za otključavanje fotki",
    "photoUnlock_body": "{handle} želi otključati fotke s tobom",
    "incomingCallVoice_title": "Dolazni glasovni poziv",
    "incomingCallVideo_title": "Dolazni video poziv",
    "incomingCall_body": "{handle} te zove",
    "likeRejected_title": "Ovaj put nije spoj",
    "likeRejected_body": "{handle} je propustio/la tvoj lajk",
    "newLike_title": "Novi lajk!",
    "newSuperLike_title": "Novi Super lajk!",
    "newLike_body": "{handle} je lajkao/la tvoj profil",
    "newMatch_title": "Imate spoj!",
    "newMatch_body": "Spojio/la si se s {handle}",
    "weeklySuperLikes_title": "Tvoji tjedni Super lajkovi su stigli 💫",
    "weeklySuperLikes_body": "Imaš {count} Super lajkova za ovaj tjedan.",
    "weeklyBoost_title": "Tvoj tjedni Boost je spreman 🚀",
    "weeklyBoost_body": "Aktiviraj ga i skoči na vrh špila na 30 minuta.",
    "supportReply_title": "Podrška je odgovorila"
  },
  "sr": {
    "newMessage_title": "Nova poruka",
    "newMessage_body": "{handle} ti je poslao/la poruku",
    "photoUnlock_title": "Zahtev za otključavanje slika",
    "photoUnlock_body": "{handle} želi da otključa slike s tobom",
    "incomingCallVoice_title": "Dolazni glasovni poziv",
    "incomingCallVideo_title": "Dolazni video poziv",
    "incomingCall_body": "{handle} te zove",
    "likeRejected_title": "Ovaj put nije spoj",
    "likeRejected_body": "{handle} je preskočio/la tvoj lajk",
    "newLike_title": "Novi lajk!",
    "newSuperLike_title": "Novi Super lajk!",
    "newLike_body": "{handle} je lajkovao/la tvoj profil",
    "newMatch_title": "Spoj je tu!",
    "newMatch_body": "Spojio/la si se sa {handle}",
    "weeklySuperLikes_title": "Tvoji nedeljni Super lajkovi su stigli 💫",
    "weeklySuperLikes_body": "Imaš {count} Super lajkova za ovu nedelju.",
    "weeklyBoost_title": "Tvoj nedeljni Boost je spreman 🚀",
    "weeklyBoost_body": "Aktiviraj ga i skoči na vrh špila na 30 minuta.",
    "supportReply_title": "Podrška je odgovorila"
  },
  "bs": {
    "newMessage_title": "Nova poruka",
    "newMessage_body": "{handle} ti je poslao/la poruku",
    "photoUnlock_title": "Zahtjev za otključavanje slika",
    "photoUnlock_body": "{handle} želi otključati slike s tobom",
    "incomingCallVoice_title": "Dolazni glasovni poziv",
    "incomingCallVideo_title": "Dolazni video poziv",
    "incomingCall_body": "{handle} te zove",
    "likeRejected_title": "Ovaj put nije spoj",
    "likeRejected_body": "{handle} je preskočio/la tvoj lajk",
    "newLike_title": "Novi lajk!",
    "newSuperLike_title": "Novi Super lajk!",
    "newLike_body": "{handle} je lajkao/la tvoj profil",
    "newMatch_title": "Imate spoj!",
    "newMatch_body": "Spojio/la si se s {handle}",
    "weeklySuperLikes_title": "Tvoji sedmični Super lajkovi su stigli 💫",
    "weeklySuperLikes_body": "Imaš {count} Super lajkova za ovu sedmicu.",
    "weeklyBoost_title": "Tvoj sedmični Boost je spreman 🚀",
    "weeklyBoost_body": "Aktiviraj ga i skoči na vrh špila na 30 minuta.",
    "supportReply_title": "Podrška je odgovorila"
  },
  "bg": {
    "newMessage_title": "Ново съобщение",
    "newMessage_body": "{handle} ти изпрати съобщение",
    "photoUnlock_title": "Заявка за отключване на снимки",
    "photoUnlock_body": "{handle} иска да отключи снимки с теб",
    "incomingCallVoice_title": "Входящо гласово обаждане",
    "incomingCallVideo_title": "Входящо видео обаждане",
    "incomingCall_body": "{handle} ти се обажда",
    "likeRejected_title": "Този път не е мач",
    "likeRejected_body": "{handle} пропусна твоя лайк",
    "newLike_title": "Нов лайк!",
    "newSuperLike_title": "Нов Супер лайк!",
    "newLike_body": "{handle} хареса профила ти",
    "newMatch_title": "Имате мач!",
    "newMatch_body": "Имаш мач с {handle}",
    "weeklySuperLikes_title": "Седмичните ти Супер лайкове са тук 💫",
    "weeklySuperLikes_body": "Имаш {count} Супер лайка за тази седмица.",
    "weeklyBoost_title": "Седмичният ти Boost е готов 🚀",
    "weeklyBoost_body": "Активирай го и скочи на върха на тестето за 30 минути.",
    "supportReply_title": "Поддръжката отговори"
  },
  "uk": {
    "newMessage_title": "Нове повідомлення",
    "newMessage_body": "{handle} надіслав(-ла) тобі повідомлення",
    "photoUnlock_title": "Запит на розблокування фото",
    "photoUnlock_body": "{handle} хоче розблокувати фото з тобою",
    "incomingCallVoice_title": "Вхідний голосовий дзвінок",
    "incomingCallVideo_title": "Вхідний відеодзвінок",
    "incomingCall_body": "{handle} тобі телефонує",
    "likeRejected_title": "Цього разу не збіг",
    "likeRejected_body": "{handle} пропустив(-ла) твій лайк",
    "newLike_title": "Новий лайк!",
    "newSuperLike_title": "Новий Супер лайк!",
    "newLike_body": "{handle} вподобав(-ла) твій профіль",
    "newMatch_title": "У вас збіг!",
    "newMatch_body": "У тебе збіг з {handle}",
    "weeklySuperLikes_title": "Твої щотижневі Супер лайки вже тут 💫",
    "weeklySuperLikes_body": "У тебе є {count} Супер лайків на цей тиждень.",
    "weeklyBoost_title": "Твій щотижневий Boost готовий 🚀",
    "weeklyBoost_body": "Активуй його і піднімись на вершину колоди на 30 хвилин.",
    "supportReply_title": "Підтримка відповіла"
  },
  "el": {
    "newMessage_title": "Νέο μήνυμα",
    "newMessage_body": "Ο/Η {handle} σου έστειλε μήνυμα",
    "photoUnlock_title": "Αίτημα ξεκλειδώματος φωτογραφιών",
    "photoUnlock_body": "Ο/Η {handle} θέλει να ξεκλειδώσει φωτογραφίες μαζί σου",
    "incomingCallVoice_title": "Εισερχόμενη φωνητική κλήση",
    "incomingCallVideo_title": "Εισερχόμενη βιντεοκλήση",
    "incomingCall_body": "Ο/Η {handle} σε καλεί",
    "likeRejected_title": "Όχι match αυτή τη φορά",
    "likeRejected_body": "Ο/Η {handle} προσπέρασε το like σου",
    "newLike_title": "Νέο Like!",
    "newSuperLike_title": "Νέο Super Like!",
    "newLike_body": "Στον/Στην {handle} άρεσε το προφίλ σου",
    "newMatch_title": "Έχετε Match!",
    "newMatch_body": "Έκανες match με τον/την {handle}",
    "weeklySuperLikes_title": "Τα εβδομαδιαία σου Super Likes έφτασαν 💫",
    "weeklySuperLikes_body": "Έχεις {count} Super Likes για αυτή την εβδομάδα.",
    "weeklyBoost_title": "Το εβδομαδιαίο σου Boost είναι έτοιμο 🚀",
    "weeklyBoost_body": "Ενεργοποίησέ το για να ανέβεις στην κορυφή για 30 λεπτά.",
    "supportReply_title": "Η υποστήριξη απάντησε"
  },
  "th": {
    "newMessage_title": "ข้อความใหม่",
    "newMessage_body": "{handle} ส่งข้อความถึงคุณ",
    "photoUnlock_title": "คำขอปลดล็อกรูปภาพ",
    "photoUnlock_body": "{handle} อยากปลดล็อกรูปภาพกับคุณ",
    "incomingCallVoice_title": "สายเรียกเข้าแบบเสียง",
    "incomingCallVideo_title": "สายเรียกเข้าแบบวิดีโอ",
    "incomingCall_body": "{handle} กำลังโทรหาคุณ",
    "likeRejected_title": "ยังไม่แมตช์ในครั้งนี้",
    "likeRejected_body": "{handle} ปัดผ่านไลก์ของคุณ",
    "newLike_title": "ไลก์ใหม่!",
    "newSuperLike_title": "ซูเปอร์ไลก์ใหม่!",
    "newLike_body": "{handle} ถูกใจโปรไฟล์ของคุณ",
    "newMatch_title": "แมตช์กันแล้ว!",
    "newMatch_body": "คุณแมตช์กับ {handle}",
    "weeklySuperLikes_title": "ซูเปอร์ไลก์รายสัปดาห์ของคุณมาแล้ว 💫",
    "weeklySuperLikes_body": "คุณมีซูเปอร์ไลก์ {count} ครั้งให้ใช้ในสัปดาห์นี้",
    "weeklyBoost_title": "บูสต์รายสัปดาห์ของคุณพร้อมแล้ว 🚀",
    "weeklyBoost_body": "เปิดใช้งานเพื่อขึ้นไปอยู่บนสุดนาน 30 นาที",
    "supportReply_title": "ฝ่ายสนับสนุนตอบกลับแล้ว"
  },
  "vi": {
    "newMessage_title": "Tin nhắn mới",
    "newMessage_body": "{handle} đã gửi tin nhắn cho bạn",
    "photoUnlock_title": "Yêu cầu mở khóa ảnh",
    "photoUnlock_body": "{handle} muốn mở khóa ảnh với bạn",
    "incomingCallVoice_title": "Cuộc gọi thoại đến",
    "incomingCallVideo_title": "Cuộc gọi video đến",
    "incomingCall_body": "{handle} đang gọi cho bạn",
    "likeRejected_title": "Chưa khớp lần này",
    "likeRejected_body": "{handle} đã bỏ qua lượt thích của bạn",
    "newLike_title": "Lượt thích mới!",
    "newSuperLike_title": "Super Like mới!",
    "newLike_body": "{handle} đã thích hồ sơ của bạn",
    "newMatch_title": "Khớp rồi!",
    "newMatch_body": "Bạn đã khớp với {handle}",
    "weeklySuperLikes_title": "Super Like hằng tuần của bạn đã có 💫",
    "weeklySuperLikes_body": "Bạn có {count} Super Like để dùng trong tuần này.",
    "weeklyBoost_title": "Boost hằng tuần của bạn đã sẵn sàng 🚀",
    "weeklyBoost_body": "Kích hoạt để vươn lên đầu danh sách trong 30 phút.",
    "supportReply_title": "Bộ phận hỗ trợ đã phản hồi"
  },
  "sq": {
    "newMessage_title": "Mesazh i ri",
    "newMessage_body": "{handle} të dërgoi një mesazh",
    "photoUnlock_title": "Kërkesë për shkyçjen e fotove",
    "photoUnlock_body": "{handle} dëshiron të shkyçë fotot me ty",
    "incomingCallVoice_title": "Telefonatë zanore në hyrje",
    "incomingCallVideo_title": "Videotelefonatë në hyrje",
    "incomingCall_body": "{handle} po të telefonon",
    "likeRejected_title": "Jo përputhje këtë herë",
    "likeRejected_body": "{handle} kaloi pëlqimin tënd",
    "newLike_title": "Pëlqim i ri!",
    "newSuperLike_title": "Super Like i ri!",
    "newLike_body": "{handle} pëlqeu profilin tënd",
    "newMatch_title": "Është një përputhje!",
    "newMatch_body": "U përputhe me {handle}",
    "weeklySuperLikes_title": "Super Likes-et e tua javore mbërritën 💫",
    "weeklySuperLikes_body": "Ke {count} Super Likes për t'i përdorur këtë javë.",
    "weeklyBoost_title": "Boost-i yt javor është gati 🚀",
    "weeklyBoost_body": "Aktivizoje për t'u ngjitur në krye të listës për 30 minuta.",
    "supportReply_title": "Mbështetja u përgjigj"
  },
  "lv": {
    "newMessage_title": "Jauna ziņa",
    "newMessage_body": "{handle} tev nosūtīja ziņu",
    "photoUnlock_title": "Fotoattēlu atbloķēšanas pieprasījums",
    "photoUnlock_body": "{handle} vēlas atbloķēt fotoattēlus ar tevi",
    "incomingCallVoice_title": "Ienākošs balss zvans",
    "incomingCallVideo_title": "Ienākošs video zvans",
    "incomingCall_body": "{handle} tev zvana",
    "likeRejected_title": "Šoreiz nav sakritības",
    "likeRejected_body": "{handle} noraidīja tavu simpātiju",
    "newLike_title": "Jauna simpātija!",
    "newSuperLike_title": "Jauna Super simpātija!",
    "newLike_body": "{handle} novērtēja tavu profilu",
    "newMatch_title": "Sakritība!",
    "newMatch_body": "Tev ir sakritība ar {handle}",
    "weeklySuperLikes_title": "Tavas iknedēļas Super simpātijas ir klāt 💫",
    "weeklySuperLikes_body": "Šonedēļ tev ir {count} Super simpātijas, ko izmantot.",
    "weeklyBoost_title": "Tavs iknedēļas Boost ir gatavs 🚀",
    "weeklyBoost_body": "Aktivizē to, lai uz 30 minūtēm izlektu klāja augšgalā.",
    "supportReply_title": "Atbalsts atbildēja"
  },
  "lt": {
    "newMessage_title": "Nauja žinutė",
    "newMessage_body": "{handle} atsiuntė tau žinutę",
    "photoUnlock_title": "Nuotraukų atrakinimo prašymas",
    "photoUnlock_body": "{handle} nori atrakinti nuotraukas su tavimi",
    "incomingCallVoice_title": "Skambutis balsu",
    "incomingCallVideo_title": "Vaizdo skambutis",
    "incomingCall_body": "{handle} tau skambina",
    "likeRejected_title": "Šįkart ne pora",
    "likeRejected_body": "{handle} atmetė tavo patiktuką",
    "newLike_title": "Naujas patiktukas!",
    "newSuperLike_title": "Naujas Super patiktukas!",
    "newLike_body": "{handle} įvertino tavo profilį",
    "newMatch_title": "Judu pora!",
    "newMatch_body": "Susiporavai su {handle}",
    "weeklySuperLikes_title": "Tavo savaitiniai Super patiktukai jau čia 💫",
    "weeklySuperLikes_body": "Šią savaitę turi {count} Super patiktukų.",
    "weeklyBoost_title": "Tavo savaitinis Boost paruoštas 🚀",
    "weeklyBoost_body": "Aktyvuok jį ir 30 minučių šok į kaladės viršų.",
    "supportReply_title": "Palaikymas atsakė"
  },
  "fi": {
    "newMessage_title": "Uusi viesti",
    "newMessage_body": "{handle} lähetti sinulle viestin",
    "photoUnlock_title": "Kuvien avauspyyntö",
    "photoUnlock_body": "{handle} haluaa avata kuvat kanssasi",
    "incomingCallVoice_title": "Saapuva äänipuhelu",
    "incomingCallVideo_title": "Saapuva videopuhelu",
    "incomingCall_body": "{handle} soittaa sinulle",
    "likeRejected_title": "Ei matchia tällä kertaa",
    "likeRejected_body": "{handle} ohitti tykkäyksesi",
    "newLike_title": "Uusi tykkäys!",
    "newSuperLike_title": "Uusi Super-tykkäys!",
    "newLike_body": "{handle} tykkäsi profiilistasi",
    "newMatch_title": "Match!",
    "newMatch_body": "Match sinun ja {handle} välillä",
    "weeklySuperLikes_title": "Viikoittaiset Super-tykkäyksesi ovat täällä 💫",
    "weeklySuperLikes_body": "Sinulla on {count} Super-tykkäystä käytettäväksi tällä viikolla.",
    "weeklyBoost_title": "Viikoittainen Boostisi on valmis 🚀",
    "weeklyBoost_body": "Aktivoi se ja nouse pakan kärkeen 30 minuutiksi.",
    "supportReply_title": "Tuki vastasi"
  },
  "hu": {
    "newMessage_title": "Új üzenet",
    "newMessage_body": "{handle} üzenetet küldött neked",
    "photoUnlock_title": "Fotófeloldási kérés",
    "photoUnlock_body": "{handle} fel szeretné oldani veled a fotókat",
    "incomingCallVoice_title": "Bejövő hanghívás",
    "incomingCallVideo_title": "Bejövő videóhívás",
    "incomingCall_body": "{handle} hív téged",
    "likeRejected_title": "Most nem jött össze",
    "likeRejected_body": "{handle} elutasította a lájkodat",
    "newLike_title": "Új lájk!",
    "newSuperLike_title": "Új Super lájk!",
    "newLike_body": "{handle} kedvelte a profilodat",
    "newMatch_title": "Match van!",
    "newMatch_body": "Match {handle} személlyel",
    "weeklySuperLikes_title": "Megjöttek a heti Super lájkjaid 💫",
    "weeklySuperLikes_body": "Ezen a héten {count} Super lájkod van.",
    "weeklyBoost_title": "Kész a heti Boostod 🚀",
    "weeklyBoost_body": "Aktiváld, és 30 percre ugorj a pakli tetejére.",
    "supportReply_title": "A támogatás válaszolt"
  }
};
